### ISSUE TITLE
Failed to load dynamic library 'editor_api.dll'

### ISSUE THREAD

**Issue by drophouse01** [icedman/flutter_editor#6]
Hi @icedman, Thanks for writing this lib. I'm trying to run it on windows. But it shows this error.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'editor_api.dll': error code 126
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      FFIBridge.load (package:editor/services/ffi/bridge.dart:34:27)
#3      main (package:editor/main.dart:31:13)
<asynchronous suspension>
```

**Comment by jonahzheng** [comment]
the same problem.
